### ISSUE TITLE
Suggestion on code snippets

### ISSUE THREAD

**Issue by cormachogan** [brito-rafa/k8s-webhooks#1]
Hey Rafa,

This is really excellent and I can see it being a super tool to teach people the basics of operators. I will certainly use this for future initiatives.

I did have some feedback in the code snippets to create the CRD & controller in the initial part of the tutorial - I wondered if we could make them code complete in the README so that users could just copy the snippets rather than replacing the complete modules, such as the controller and types files?

In the **controllers/rockband_controller.go**, it only needs a few additional imports and adding the ctx and log vars, e.g.

```
import (
        "context"
        “fmt"
        “strconv"
        “time”

        "github.com/go-logr/logr”
        k8serr "k8s.io/apimachinery/pkg/api/errors"
        "k8s.io/apimachinery/pkg/runtime"
        ctrl "sigs.k8s.io/controller-runtime"
        "sigs.k8s.io/controller-runtime/pkg/client"

func (r *RockBandReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
        ctx :=** context.Background()
        log :=** r.Log.WithValues("rockband", req.NamespacedName)

        // your logic here
```

In the  **api/v1/rockband_types.go**, we just need to add the following:

```
< // +kubebuilder:validation:Optional
< // +kubebuilder:resource:shortName={"rb"}
< // +kubebuilder:printcolumn:name="Genre",type=string,JSONPath=`.spec.genre`
< // +kubebuilder:printcolumn:name="Number_Components",type=integer,JSONPath=`.spec.numberComponents`
< // +kubebuilder:printcolumn:name="Lead_Singer",type=string,JSONPath=`.spec.leadSinger`

< // +kubebuilder:subresource:status
< // +kubebuilder:storageversion
```

With these few additions to the snippets, there would no need to context switch out to the code examples, and allow readers to run through the exercise from start to end.

**Comment by brito-rafa** [comment]
Thanks for the feedback!!! I just added those lines. Please keep them coming!
