### ISSUE TITLE
Suggestion on code snippets - webhook

### ISSUE THREAD

**Issue by cormachogan** [brito-rafa/k8s-webhooks#2]
Include the additional imports in api/v1/rockband_webhook.go code snippet

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/util/validation/field"

**Comment by brito-rafa** [comment]
Done - thanks!!!!
